services:
  db:
    image: postgres:17.5
    container_name: realtycomps_db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: realtycomps
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realtycomps_web
    ports:
      - '3002:3000'
    depends_on:
      - db

volumes:
  db_data:
